security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator endpoints

logging: 
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true

quoteServiceURL: http://localhost:8080/quote
